[versions]
appcompat = "1.7.0"
ats = "v2.8.0"
constraintlayout = "2.2.0"
coreKtx = "1.15.0"
espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
material = "1.12.0"
preferenceKtx = "1.2.1"
agp = "8.2.2"
kotlin = "1.9.22"


[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
ats = { module = "com.liveramp:ats", version.ref = "ats" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
